db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=${PGUSER}
        - POSTGRES_PASSWORD=${PGPASSWORD}
        - POSTGRES_DB=${PGDATABASE}
    expose: 
        - 5432
server:
    build: .
    restart: always
    environment:
        - TOKEN_SECRET=${TOKEN_SECRET}
        - PGUSER=${PGUSER}
        - PGPASSWORD=${PGPASSWORD}
        - PGHOST=host.docker.internal
        - PGPORT=5432,
        - PGDATABASE=${PGDATABASE}
    ports: 
        - 5000:5000
    links: 
        - db